RWA_MI2_IvanKozul_2RP1/RWA_MI2_IvanKozul_2RP1/Controllers/DrzaveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RWA_MI2_IvanKozul_2RP1.Models;
using RWA_MI2_IvanKozul_2RP1.DAL;
using System.Text;

namespace RWA_MI2_IvanKozul_2RP1.Controllers
{
    public class DrzaveController : Controller
    {
        private AdventureWorksRWAEntities1 db = new AdventureWorksRWAEntities1();

        // GET: Drzave
        public ActionResult Index()
        {
            ViewBag.ReUrl = Url.Action("Kupac", "Home");
            return View(db.Drzave.ToList());
        }

        [HttpGet]
        public string CityList(string id)
        {
            Repo repo = new Repo();
            List<Grad> lg = repo.GetCityById(Int32.Parse(id));
            StringBuilder sb = new StringBuilder();
            lg.ForEach(i => sb.Append(i.Naziv + ","));
            return sb.ToString().Remove(sb.ToString().Length-1);

        }


        // GET: Drzave/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drzava drzava = db.Drzave.Find(id);
            if (drzava == null)
            {
                return HttpNotFound();
            }
            return View(drzava);
        }

        // GET: Drzave/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drzave/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDDrzava,Naziv")] Drzava drzava)
        {
            if (ModelState.IsValid)
            {
                db.Drzave.Add(drzava);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(drzava);
        }

        // GET: Drzave/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drzava drzava = db.Drzave.Find(id);
            if (drzava == null)
            {
                return HttpNotFound();
            }
            return View(drzava);
        }

        // POST: Drzave/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDDrzava,Naziv")] Drzava drzava)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drzava).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(drzava);
        }

        // GET: Drzave/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drzava drzava = db.Drzave.Find(id);
            if (drzava == null)
            {
                return HttpNotFound();
            }
            return View(drzava);
        }

        // POST: Drzave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Drzava drzava = db.Drzave.Find(id);
            db.Drzave.Remove(drzava);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RWA_MI2_IvanKozul_2RP1/RWA_MI2_IvanKozul_2RP1/Controllers/LoginController.cs
using RWA_MI2_IvanKozul_2RP1.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RWA_MI2_IvanKozul_2RP1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public string GetLoginRole(string username, string pass)
        {
            Repo repo = new Repo();
            string returnValue = repo.CheckLogin(username, pass).ToString();

            Session["UserRole"] = returnValue;

            return returnValue;
        }

        [HttpGet]
        public string GetRole()
        {
            return Session["UserRole"].ToString();
        }
    }
}

RWA_MI2_IvanKozul_2RP1/RWA_MI2_IvanKozul_2RP1/Views/Login/Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @using System.Web.Optimization
    @Scripts.Render("~/bundles/layout")
    @Styles.Render("~/bundles/Style/layout")

    <script>
        $(function () {
            $('#loginBtn').click(function () {
                var username = $('#korisnikoIme').val();
                var pass = $('#pass').val();

                $.ajax({
                    url: '@Url.Action("GetLoginRole", "Login")',
                    data: {
                        username: username,
                        pass: pass
                    },
                    success: function (msg) {
                        var role = GetRole();
                    },
                    error: function (e) {
                        console.log(e.statusText);
                    }
                        });
            });

            $('#role').click(function () {
                GetRole();
            });
        });

        function GetRole() {
             $.ajax({
                    url: '@Url.Action("GetRole", "Login")',
                    success: function (msg) {
                        
                        if (msg != '-1') {
                            window.location.replace("@Url.Action("Index", "Drzave")");
                        }
                        else {
                            $('#errorMsg').html('Korisnik s tim imenom i lozinkom ne postoji!');
                        }
                        return msg.toString();
                    },
                    error: function (e) {
                        console.log(e.statusText);
                    }
                        });
        }
    </script>
</head>
<body>
    <div class="jumbotron text-capitalize">AdventureWorks Administracija
    </div>

    <div class="container" style="width:300px; align-content:center;">
        <label>Korisnicko Ime: </label>
        <input type="text" name="korisnikoIme" value="" id="korisnikoIme" class="form-control" />
        <br />
        <label>Lozinka: </label>
        <input type = "password" name = "pass" value = "" id = "pass" class="form-control" />
        <br />
        <div id="errorMsg"></div>
        <br />
        <a href="#" class="btn btn-dark" style="width:100%;" id="loginBtn">Login</a>
        <a href="#" class="btn btn-dark d-none" style="width:100%;" id="role">getrole</a>
    </div>
</body>
</html>

<style>
    .jumbotron {
        margin:0 auto;
        margin-top:50px;
        width:600px;
        height: 80px;
        padding-bottom: 40px;
        padding-top: 40px;
        background-color: #404040;
        font-size: large;
        color: white;
    }
</style>